import subprocess
from pathlib import Path

from AICatalysis.common.constant import ChemInfo
from database.reaxys import Reaxys


class Gaussian(object):
    pass


class GJFFile(object):
    def __init__(self, task="opt", method="b3lyp/6-31g(d,p)"):
        self.task = task
        self.method = method

    def read(self):
        pass

    def write(self, smiles: str, file='input.gjf'):
        process = subprocess.Popen(f"obabel -:{smiles} --gen3d -ogjf", stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        content = process.stdout.read().decode(encoding='utf-8')
        lines = content.splitlines()
        chk_path = Path("").absolute() / Path(f"{file.removesuffix('.gjf')}.chk")
        lines[0] = f"%chk={chk_path}"
        lines[1] = f"#{self.task} {self.method}"
        lines[3] = "AutoGenerated"
        with open(file, "w") as f:
            f.write("\n".join(lines))


if __name__ == '__main__':
    mapping = Reaxys.get_reaction_mapping()
    catalysts = [name for name in list(mapping[0].keys()) if ChemInfo[name].get("smiles", None) is not None]
    catalysts_smiles = [ChemInfo[name]['smiles'] for name in catalysts]
    gjf = GJFFile()
    for item, name in zip(catalysts_smiles, catalysts):
        print(f"{name}.gjf has been written")
        gjf.write(smiles=item, file=f"{name}.gjf")
    print()
