import subprocess
from pathlib import Path

import numpy as np

from AICatalysis.common.constant import ChemInfo
from AICatalysis.database.reaxys import Reaxys


class Gaussian(object):
    pass


class GJFFile(object):
    def __init__(self, task="opt", method="b3lyp/6-31g(d,p)"):
        self.task = task
        self.method = method

    def read(self):
        pass

    def write(self, smiles: str, file='input.gjf'):
        process = subprocess.Popen(f"obabel -:{smiles} --gen3d -ogjf", stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        content = process.stdout.read().decode(encoding='utf-8')
        lines = content.splitlines()
        chk_path = Path("").absolute() / Path(f"{file.removesuffix('.gjf')}.chk")
        lines[0] = f"%chk={chk_path}"
        lines[1] = f"#{self.task} {self.method}"
        lines[3] = "AutoGenerated"
        with open(file, "w") as f:
            f.write("\n".join(lines))


class OUTFile(object):
    def __init__(self, name="result.out"):
        self.name = name
        self.input_atoms = None
        self.mulliken_charge = None
        self.dipole_moment = None
        self.homo, self.lumo = None, None
        self.homo_index, self.lumo_index = None, None

    def read(self):
        with open(self.name, "r") as f:
            self._strings = f.readlines()

        # read input_atoms
        lns, lne = None, None
        for index, line in enumerate(self._strings):
            if line.startswith(" Symbolic Z-matrix"):
                lns = index
            elif line.startswith(" GradGrad"):
                lne = index
            if lns is not None and lne is not None:
                break

        _format = lambda x: [str(x[0]), float(x[1]), float(x[2]), float(x[3])]
        atom_lines = [l.split() for l in self._strings[lns + 2:lne - 2]]
        self.input_atoms = list(map(_format, atom_lines))

        # read Mulliken charges
        mulliken_index = [index for index, line in enumerate(self._strings) if line.startswith(" Mulliken charges:")]
        mulliken_charge = self._strings[mulliken_index[-1] + 2:mulliken_index[-1] + 2 + len(self.input_atoms)]
        self.mulliken_charge = [float(line.split()[2]) for line in mulliken_charge]

        # read Dipole moment
        dipole_index = [index for index, line in enumerate(self._strings) if line.startswith(" Dipole moment")][-1] + 1
        dipole_moment = list(map(float, self._strings[dipole_index].split()[1::2]))
        self.dipole_moment = {"X": dipole_moment[0], "Y": dipole_moment[1], "Z": dipole_moment[2],
                              "Tot": dipole_moment[3]}

        # read HOMO/LUMO
        orb_s_index = [index for index, line in enumerate(self._strings) if line.startswith(" The electronic state")][
                          -1] + 1
        orb_e_index = [index for index, line in enumerate(self._strings) if
                       line.startswith("          Condensed to atoms")][-1]
        orbital_occ = list(map(float,
                               sum([line.split("--")[1].split() for line in self._strings[orb_s_index:orb_e_index] if
                                    "occ." in line], [])))
        orbital_virt = list(map(float,
                                sum([line.split("--")[1].split() for line in self._strings[orb_s_index:orb_e_index] if
                                     "virt." in line], [])))
        self.homo, self.homo_index = orbital_occ[-1], len(orbital_occ) - 1
        self.lumo, self.lumo_index = orbital_virt[0], len(orbital_occ)
        return self


class FCHKFile(object):
    def __init__(self, name="result.fchk"):
        self.name = name
        self.coeff = None

    def read(self):
        with open(self.name, "r") as f:
            self._strings = f.readlines()

        # read Alpha MO coefficients
        basis_num, lns, lne = None, -1, -1
        for index, line in enumerate(self._strings):
            if line.startswith("Number of basis functions"):
                basis_num = int(line.split()[-1])
            elif line.startswith("Alpha MO coefficients"):
                lns = index
            elif line.startswith("Orthonormal basis"):
                lne = index
                break
        coeff = list(map(float, sum([line.split() for line in self._strings[lns + 1:lne]], [])))
        coeff = np.array(coeff).reshape((basis_num, -1))
        self.coeff = coeff

        return self


if __name__ == '__main__':
    # mapping = Reaxys.get_reaction_mapping()
    # catalysts = [name for name in list(mapping[0].keys()) if ChemInfo[name].get("smiles", None) is not None]
    # catalysts_smiles = [ChemInfo[name]['smiles'] for name in catalysts]
    # gjf = GJFFile()
    # for item, name in zip(catalysts_smiles, catalysts):
    #     print(f"{name}.gjf has been written")
    #     gjf.write(smiles=item, file=f"{name}.gjf")
    # print()
    out = OUTFile("../database/chemical-gjf/Ac2O.out")
    out.read()
    fchk = FCHKFile("../database/chemical-gjf/Ac2O.fchk")
    fchk.read()
    pass
